### ISSUE TITLE
Differentiate between testing and production release

### ISSUE THREAD

**Issue by busterbeam** [PaperMC/bibliothek#46]
I am building a maintenance system that should updates builds but hopefully updates versions as well but I noticed the API does not state if that the latest version is still in testing.  if some Identifier could be added, at least in the message or summary of the build stating it's test version.  I will have an option in my program `.ini` to only warn for new updates but not act, but if this piece of the API response could be added I would appreciate that.

**Comment by Viqsi** [comment]
I don't think the PaperMC project even *has* a concept of "release" versus "testing". If there is, it's impossible to tell from the downloads page. I just only ever see a list of per-commit builds.

I had assumed for quite some time that there was some sort of project discipline or QC to keep new commits from breaking things, but the recent "auto-updaters are strictly forbidden" change seems to suggest otherwise and simultaneously indicate there's a complete lack of interest in addressing that issue.

**Comment by kashike** [comment]
Yeah, that's totally why I recently added [channels and promoted builds](https://github.com/PaperMC/bibliothek/commit/faae0ae589ce6e5414d6cea8c6f66784be9f94f5).

**Comment by electronicboy** [comment]
Auto updaters have been frowned upon for years, nothing has changed in that regard

This is a project which relies upon multiple upstream projects of which don't have a proper lifecycle either, as much as I love the sponge peeps, I also don't feel that there is much of a need to adopt a recommended build setup where you have recommended builds or a "production" style branch and then have a separate branch for pulling stuff into, this is far too much of a volatile environment with changes especially when many times people won't/can't run the RBs due to needing fixes on the dev branch, not to mention the drastic increase of dev time that would be required for this given the project setup, etc

larger patches are generally tested through the release of test builds, smaller patches are often tested by the devs, etc this may change in the future towards something more tenable, but will probably be a post hardfork thing if ever

**Comment by Viqsi** [comment]
> Yeah, that's totally why I recently added [channels and promoted builds](https://github.com/PaperMC/bibliothek/commit/faae0ae589ce6e5414d6cea8c6f66784be9f94f5).

Mea culpa, apparently. Is there anywhere else this could be found outside of that commit log? I was literally searching for weeks for something exactly like this and couldn't find it, so I'm kind of wondering if this is a "documentation needs a fix" issue or a "Viqsi can't see her hand in front of her face" issue.

**Comment by electronicboy** [comment]
only velocity currently uses this mechanism given the issues above
